<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Glyphs.json.gz"/>
    <EmbeddedResource Include="Scout.png"/>
    <EmbeddedResource Include="lettherebelight.txt"/>
    <EmbeddedResource Include="powerinfaith.txt"/>    
  </ItemGroup>
</Project>
